version: "3.3" # docker-compose --version
services:
  xnode: # image
    build: ./xnode
    image: xnode:v1
    working_dir: /xxnode
    container_name: xxnode_c
    ports:
      - '4000:4000'
    volumes:
      - ./xnode:/xxnode
      - ./xnode/node_modules:/xxnode/node_modules
    stdin_open: true # STDIN stream open for a container
  xreact: # image
    build: ./xreact
    image: xreact:v1
    working_dir: /xxreact
    container_name: xxreact_c
    ports:
      - '3000:3000'
    volumes:
      - ./xreact:/xxreact
      - ./xreact/node_modules:/xxreact/node_modules
    stdin_open: true # STDIN stream open for a container
