name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  xnode:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Npm run
        run: |
          cd ./xnode
          npm install

  xreact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Npm run
        run: |
          cd ./xreact
          npm install
          npm run test
          npm run build
